### ISSUE TITLE
Can't install on v0.15.1

### ISSUE THREAD

**Issue by amitaibu** [rgrempel/elm-route-hash#8]
Not sure if it only on my system, but when I switched back to 0.15.1 and tried to re-install my project it didn't work. Only when change `elm-package.json` to:

`"rgrempel/elm-route-hash": "1.0.4 <= v < 1.0.5"` it worked fine.

**Comment by rgrempel** [comment]
I think the problem is that version 1.0.5 isn't claiming back-compatibility with Elm 0.15. So, trying to install version 1.0.5 with Elm 0.15 just isn't going to work.

By itself, I think that elm-route-hash is actually potentially compatible with both 0.15 and 0.16. However, several dependencies are not back-compatible with Elm 0.16, so you really do need 1.0.4 with Elm 0.15.

What happens if you use this:

```
"rgrempel/elm-route-hash": "1.0.4 <= v < 2.0.0"
```

In theory, I'd hope that this installs 1.0.4 in Elm 0.15 and 1.0.5 in Elm 0.16. But maybe it doesn't do that ... actually, I suppose I can check myself.

**Comment by rgrempel** [comment]
Here's an example of an elm-package.json file which installs 1.0.4 under Elm 0.15 and 1.0.5 under Elm 0.16:

``` json
{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/USER/project.git",
    "license": "BSD3",
    "source-directories": [
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "2.0.0 <= v < 4.0.0",
        "rgrempel/elm-route-hash": "1.0.4 <= v < 2.0.0"
    },
    "elm-version": "0.15.1 <= v < 0.17.0"
}
```

That being said, if there's anything I can adjust in the way I express my dependencies in 1.0.5 that helps, I'd be happy to look at that.

**Comment by amitaibu** [comment]
:+1:
